### ISSUE TITLE
Similarity based on Average kernel obtain deferent value between each atom and its replica atoms.

### ISSUE THREAD

**Issue by Firaskigali** [SINGROUP/dscribe#128] opened 2023-10-29 11:51 UTC
Dear all,

This might be an "issue".

I want to know why the SOAP descriptor available in the current version of Dscribe represents an atom and its corresponding replica atoms (of the same species) differently, which leads to different similarity values between those atoms (an atom with its corresponding replica atoms when using the average kernel).  For example, if we have a unit cell of a monoclynic or glassy system, a supercell is obtained by replicating the unit cell 2*2*2 in three-dimensional space. The SOAP descriptor is computed for both unit and super cells (using the same setup).  When we measure the similarity between atom X in the unit cell and its corresponding 8 replica atoms in the super cell (using the average kernel as implemented in Dscribe software), The output shows that this atom X is different from its replica atoms (though they are symmetric).

Do you know an explanation of this or any modifications or post-processing that can be done to enable the kernel output to be identical? Please let me know if this makes sense.

Thanks!

**Comment by lauri-codes** [comment] 2023-11-13 21:16
Closing as duplicate of #129.

**Closed by lauri-codes** 2023-11-13 21:16 UTC
