### ISSUE TITLE
Error installing with MacOS

### ISSUE THREAD

**Issue by ardunn** [SINGROUP/dscribe#8] opened 2018-12-27 07:57 UTC
Installing from `pip install dscribe` and also trying from source, my install fails at compilation with:

```
pip install . -e

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument
(common_env3) ardunn@ardmbp:~/alex/lbl/projects/common_env/dev_codes/dscribe$ pip install -e .
Obtaining file:///Users/ardunn/alex/lbl/projects/common_env/dev_codes/dscribe
Requirement already satisfied: numpy in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from dscribe==0.1.7) (1.15.2)
Requirement already satisfied: scipy in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from dscribe==0.1.7) (1.1.0)
Requirement already satisfied: ase in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from dscribe==0.1.7) (3.11.0)
Requirement already satisfied: future in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from dscribe==0.1.7) (0.16.0)
Requirement already satisfied: matplotlib in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from dscribe==0.1.7) (2.2.2)
Collecting soaplite==0.14.7 (from dscribe==0.1.7)
  Downloading https://files.pythonhosted.org/packages/ab/48/5a91b5e67ce206f4b7124b53c273e9c5b12e35e098f05f09284f03f1eaff/soaplite-0.14.7.tar.gz (44kB)
    100% |████████████████████████████████| 51kB 853kB/s 
Requirement already satisfied: six>=1.10 in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from matplotlib->dscribe==0.1.7) (1.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from matplotlib->dscribe==0.1.7) (2.2.0)
Requirement already satisfied: cycler>=0.10 in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from matplotlib->dscribe==0.1.7) (0.10.0)
Requirement already satisfied: pytz in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from matplotlib->dscribe==0.1.7) (2018.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from matplotlib->dscribe==0.1.7) (1.0.1)
Requirement already satisfied: python-dateutil>=2.1 in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from matplotlib->dscribe==0.1.7) (2.7.3)
Requirement already satisfied: setuptools in /Users/ardunn/alex/lbl/projects/common_env/common_env3/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib->dscribe==0.1.7) (40.6.3)
Building wheels for collected packages: soaplite
  Running setup.py bdist_wheel for soaplite ... done
  Stored in directory: /Users/ardunn/Library/Caches/pip/wheels/71/76/df/bffb095ad62591a3b3b9dbae7c45923b683bd53c0bf802c479
Successfully built soaplite
Installing collected packages: soaplite, dscribe
  Found existing installation: dscribe 0.1.7
    Not uninstalling dscribe at /Users/ardunn/alex/lbl/projects/common_env/dev_codes/dscribe, outside environment /Users/ardunn/alex/lbl/projects/common_env/common_env3
    Can't uninstall 'dscribe'. No files were found to uninstall.
  Running setup.py develop for dscribe
    Complete output from command /Users/ardunn/alex/lbl/projects/common_env/common_env3/bin/python3 -c "import setuptools, tokenize;__file__='/Users/ardunn/alex/lbl/projects/common_env/dev_codes/dscribe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing dscribe.egg-info/PKG-INFO
    writing dependency_links to dscribe.egg-info/dependency_links.txt
    writing requirements to dscribe.egg-info/requires.txt
    writing top-level names to dscribe.egg-info/top_level.txt
    reading manifest file 'dscribe.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'LICENSE.txt'
    writing manifest file 'dscribe.egg-info/SOURCES.txt'
    running build_ext
    building 'dscribe.libacsf.libacsf' extension
    creating build
    creating build/temp.macosx-10.6-intel-3.6
    creating build/temp.macosx-10.6-intel-3.6/dscribe
    creating build/temp.macosx-10.6-intel-3.6/dscribe/libacsf
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Idscribe/libacsf -I/Users/ardunn/alex/lbl/projects/common_env/common_env3/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c dscribe/libacsf/acsf-utils.c -o build/temp.macosx-10.6-intel-3.6/dscribe/libacsf/acsf-utils.o -O3 -std=c99
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Idscribe/libacsf -I/Users/ardunn/alex/lbl/projects/common_env/common_env3/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c dscribe/libacsf/acsf-compute.c -o build/temp.macosx-10.6-intel-3.6/dscribe/libacsf/acsf-compute.o -O3 -std=c99
    creating build/lib.macosx-10.6-intel-3.6
    creating build/lib.macosx-10.6-intel-3.6/dscribe
    creating build/lib.macosx-10.6-intel-3.6/dscribe/libacsf
    /usr/bin/clang -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-3.6/dscribe/libacsf/acsf-utils.o build/temp.macosx-10.6-intel-3.6/dscribe/libacsf/acsf-compute.o -o build/lib.macosx-10.6-intel-3.6/dscribe/libacsf/libacsf.cpython-36m-darwin.so
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    building 'dscribe.libmbtr.cmbtrwrapper' extension
    creating build/temp.macosx-10.6-intel-3.6/dscribe/libmbtr
    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Idscribe/libmbtr -I/Users/ardunn/alex/lbl/projects/common_env/common_env3/include -I/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c dscribe/libmbtr/cmbtrwrapper.cpp -o build/temp.macosx-10.6-intel-3.6/dscribe/libmbtr/cmbtrwrapper.o -std=c++11
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    dscribe/libmbtr/cmbtrwrapper.cpp:599:10: fatal error: 'ios' file not found
    #include "ios"
             ^~~~~
    1 warning and 1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
  Can't roll back dscribe; was not uninstalled
Command "/Users/ardunn/alex/lbl/projects/common_env/common_env3/bin/python3 -c "import setuptools, tokenize;__file__='/Users/ardunn/alex/lbl/projects/common_env/dev_codes/dscribe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/ardunn/alex/lbl/projects/common_env/dev_codes/dscribe/
```

Any ideas on how to fix this?

**Comment by ardunn** [comment] 2018-12-27 07:59
If it helps, my system specs are:

OS: OSX 10.14.2
Python: 3.6.2

**Comment by lauri-codes** [comment] 2018-12-27 10:33
Thank you for letting us know. We have just successfully tested installing on mac, but with different OS and python version. We will look into this and keep you updated.

**Comment by lauri-codes** [comment] 2018-12-27 10:41
Could you check what version of the Command Line Tools you currently have, and try updating them (see e.g. https://stackoverflow.com/questions/42538171/xcode-command-line-tools-how-to-update). If this does not help, let us know.

**Comment by ardunn** [comment] 2018-12-28 05:54
Hi @lauri-codes I have Command Line Tools 10.1

**Comment by lauri-codes** [comment] 2018-12-28 13:31
Hi @ardunn,

It seems that the issue actually comes from the newer version of Command Line Tools. At least with CLT version 9.4.1 there is no issue. We will try to resolve the issue, in the meantime downgrading CLT should help.

**Comment by lauri-codes** [comment] 2018-12-28 23:16
Hi @ardunn, 

Could you check if the problem is now fixed in the git master branch or in the newest pypi version (dscribe 0.1.8). I did manage to install everything under OSX 10.13.6, Python 2.7 and CLT: 10.1.

The problems seems to be in the compilation flags distutils uses when compiling the C++ extension included with DSCribe. Newer versions of CLT come with clang that does not support the "-std=c++11" flag used in setup.py. Instead something like "-std=libc++" should be used. I now added the extra compilation argument "-mmacosx-version-min=10.9" which seems to force backwards compatibility with the old flag.

**Comment by lauri-codes** [comment] 2019-01-23 18:11
Closing this issue for now.

**Closed by lauri-codes** 2019-01-23 18:11 UTC
