### ISSUE TITLE
NaN values in K3 of MBTR when using "angles" as the geometry function

### ISSUE THREAD

**Issue by kunalghosh** [SINGROUP/dscribe#18] opened 2019-07-12 14:00 UTC
Package versions: 
* `ase 3.17.0` 
* `dscribe 0.2.6`
* `Python 3.7.1`

Download the XYZ file : https://users.aalto.fi/~ghoshk1/data.xyz

```python
from dscribe.descriptors import MBTR


def make_mbtr_desc(atomic_numbers, max_atomic_number, min_atomic_number,
                 min_distance, decay_factor):
    mbtr_desc = MBTR(
        species=atomic_numbers,
        periodic=False,
        k1={
            "geometry": {
                "function": "atomic_number"
            },
            "grid": {
                "min": min_atomic_number,
                "max": max_atomic_number,
                "sigma": 0.2,
                "n": 200
            }
        },
        k2={
            "geometry": {
                "function": "inverse_distance"
            },
            "grid": {
                "min": 0,
                "max": 1 / min_distance,
                "sigma": 0.02,
                "n": 200,
            },
            "weighting": {
                "function": "exponential",
                "scale": decay_factor,
                "cutoff": 1e-3
            },
        },
        k3={
            "geometry": {
                "function": "angle"
            },
            "grid": {
                "min": -1.0,
                "max": 1.0,
                "sigma": 0.09,
                "n": 200,
            },
            "weighting": {
                "function": "exponential",
                "scale": decay_factor,
                "cutoff": 1e-3
            },
        },
        # flatten = False
    )

    return mbtr_desc
```

The respective variables in the MBTR definition above were obtained as follows:

```python
import ase.io
from dscribe.utils.stats import system_stats

xyz_file = "./data.xyz"
ase_atoms = list(ase.io.iread(xyz_file, format="xyz"))

# Load in statistics from the dataset
stats = system_stats(ase_atoms)
atomic_numbers = stats["atomic_numbers"]
max_atomic_number = stats["max_atomic_number"]
min_atomic_number = stats["min_atomic_number"]
min_distance = stats["min_distance"]

decay_factor = 0.5

mbtr_desc = make_mbtr_desc(atomic_numbers, max_atomic_number,
                           min_atomic_number, min_distance, decay_factor)
```

Now create the MBTR for the 26th atom and check for `Nan`

```python
m = mbtr_desc.create(ase_atoms[25])
np.isnan(m).any()
```

However, if the K3 in MBTR is definition to use `cosine` function instead of `angle` then `Nans` don't show up

**Comment by lauri-codes** [comment] 2019-07-12 17:23
Hi @kunalghosh,

Thank you for reporting the issue! The problem is now fixed in the git master branch, and the fix will be included in the next release (>= 0.2.8).

The problem was that sometimes, due to floating point imprecision, the cosine values were ever so slightly outside the range [-1, 1]. This caused NaNs when the inverse cosine was called to get the angle.

**Closed by lauri-codes** 2019-07-12 17:23 UTC
