### ISSUE TITLE
Install error with 0.3.2

### ISSUE THREAD

**Issue by sirmarcel** [SINGROUP/dscribe#42] opened 2020-02-06 13:52 UTC
Hi Lauri, I've noticed that updating `dscribe` on our HPC system leads to errors looking like this:

```
Command ['/u/csutton/conda-envs/py37/bin/python', '-m', 'pip', 'ins                                               
tall', '--no-deps', '-U', 'dscribe==0.3.2'] errored with the follow  
ing output:                                                          
Collecting dscribe==0.3.2                                            
  Downloading https://files.pythonhosted.org/packages/b8/13/ff23825  
ac17f99e3a25756a9e2b256dcf278b2dad983f2d4c16206645255/dscribe-0.3.2  
.tar.gz (185kB)                                                      
Building wheels for collected packages: dscribe                      
  Building wheel for dscribe (setup.py): started                     
  Building wheel for dscribe (setup.py): finished with status 'erro  
r'                                                                   
  ERROR: Complete output from command /u/csutton/conda-envs/py37/bi  
n/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-  
install-135uzlet/dscribe/setup.py'"'"';f=getattr(tokenize, '"'"'ope  
n'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'  
\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' b  
dist_wheel -d /tmp/pip-wheel-fvyvx8z5 --python-tag cp37:             
  ERROR: running bdist_wheel                                         
  running build                                                      
  running build_py                                                   
  creating build                                                     
  creating build/lib.linux-x86_64-3.7                                
  creating build/lib.linux-x86_64-3.7/dscribe                        
  copying dscribe/__init__.py -> build/lib.linux-x86_64-3.7/dscribe  
  creating build/lib.linux-x86_64-3.7/dscribe/core                   
  copying dscribe/core/system.py -> build/lib.linux-x86_64-3.7/dscr  
ibe/core                                                             
  copying dscribe/core/__init__.py -> build/lib.linux-x86_64-3.7/ds  
cribe/core                                                           
  copying dscribe/core/lattice.py -> build/lib.linux-x86_64-3.7/dsc  
ribe/core                                                            
  creating build/lib.linux-x86_64-3.7/dscribe/libacsf                
  copying dscribe/libacsf/__init__.py -> build/lib.linux-x86_64-3.7  
/dscribe/libacsf                                                     
  creating build/lib.linux-x86_64-3.7/dscribe/kernels                
  copying dscribe/kernels/__init__.py -> build/lib.linux-x86_64-3.7  
/dscribe/kernels                                                     
  copying dscribe/kernels/localsimilaritykernel.py -> build/lib.lin  
ux-x86_64-3.7/dscribe/kernels                                        
  copying dscribe/kernels/averagekernel.py -> build/lib.linux-x86_6  
4-3.7/dscribe/kernels                                                
  copying dscribe/kernels/rematchkernel.py -> build/lib.linux-x86_6  
4-3.7/dscribe/kernels                                                
  creating build/lib.linux-x86_64-3.7/dscribe/libmbtr                
  copying dscribe/libmbtr/__init__.py -> build/lib.linux-x86_64-3.7  
/dscribe/libmbtr                                                     
  creating build/lib.linux-x86_64-3.7/dscribe/utils                  
  copying dscribe/utils/species.py -> build/lib.linux-x86_64-3.7/ds  
cribe/utils                                                          
  copying dscribe/utils/geometry.py -> build/lib.linux-x86_64-3.7/d  
scribe/utils                                                         
  copying dscribe/utils/stats.py -> build/lib.linux-x86_64-3.7/dscr  
ibe/utils                                                            
  copying dscribe/utils/__init__.py -> build/lib.linux-x86_64-3.7/d  
scribe/utils                                                         
  creating build/lib.linux-x86_64-3.7/dscribe/descriptors            
  copying dscribe/descriptors/elementaldistribution.py -> build/lib  
.linux-x86_64-3.7/dscribe/descriptors                                
  copying dscribe/descriptors/mbtr.py -> build/lib.linux-x86_64-3.7  
/dscribe/descriptors                                                 
  copying dscribe/descriptors/coulombmatrix.py -> build/lib.linux-x  
86_64-3.7/dscribe/descriptors                                        
  copying dscribe/descriptors/__init__.py -> build/lib.linux-x86_64  
-3.7/dscribe/descriptors                                             
  copying dscribe/descriptors/sinematrix.py -> build/lib.linux-x86_  
64-3.7/dscribe/descriptors                                           
  copying dscribe/descriptors/lmbtr.py -> build/lib.linux-x86_64-3.  
7/dscribe/descriptors                                                
  copying dscribe/descriptors/ewaldsummatrix.py -> build/lib.linux-  
x86_64-3.7/dscribe/descriptors                                       
  copying dscribe/descriptors/soap.py -> build/lib.linux-x86_64-3.7  
/dscribe/descriptors                                                 
  copying dscribe/descriptors/matrixdescriptor.py -> build/lib.linu  
x-x86_64-3.7/dscribe/descriptors                                     
  copying dscribe/descriptors/acsf.py -> build/lib.linux-x86_64-3.7  
/dscribe/descriptors                                                 
  copying dscribe/descriptors/descriptor.py -> build/lib.linux-x86_  
64-3.7/dscribe/descriptors                                           
  running egg_info                                                   
  writing dscribe.egg-info/PKG-INFO                                  
  writing dependency_links to dscribe.egg-info/dependency_links.txt  
  writing requirements to dscribe.egg-info/requires.txt              
  writing top-level names to dscribe.egg-info/top_level.txt          
  reading manifest file 'dscribe.egg-info/SOURCES.txt'               
  reading manifest template 'MANIFEST.in'                            
  writing manifest file 'dscribe.egg-info/SOURCES.txt'               
  creating build/lib.linux-x86_64-3.7/dscribe/ext                    
  copying dscribe/ext/celllist.cpp -> build/lib.linux-x86_64-3.7/ds  
cribe/ext                                                            
  copying dscribe/ext/celllist.h -> build/lib.linux-x86_64-3.7/dscr  
ibe/ext                                                              
  copying dscribe/ext/ext.cpp -> build/lib.linux-x86_64-3.7/dscribe  
/ext                                                                 
  copying dscribe/ext/soapGTO.cpp -> build/lib.linux-x86_64-3.7/dsc  
ribe/ext                                                             
  copying dscribe/ext/soapGTO.h -> build/lib.linux-x86_64-3.7/dscri  
be/ext                                                               
  copying dscribe/ext/soapGeneral.cpp -> build/lib.linux-x86_64-3.7  
/dscribe/ext                                                         
  copying dscribe/ext/soapGeneral.h -> build/lib.linux-x86_64-3.7/d  
scribe/ext                                                           
  copying dscribe/libacsf/acsf.cpp -> build/lib.linux-x86_64-3.7/ds  
cribe/libacsf                                                        
  copying dscribe/libacsf/acsf.h -> build/lib.linux-x86_64-3.7/dscr  
ibe/libacsf                                                          
  copying dscribe/libacsf/acsfwrapper.cpp -> build/lib.linux-x86_64  
-3.7/dscribe/libacsf                                                 
  copying dscribe/libmbtr/mbtr.cpp -> build/lib.linux-x86_64-3.7/ds  
cribe/libmbtr                                                        
  copying dscribe/libmbtr/mbtr.h -> build/lib.linux-x86_64-3.7/dscr  
ibe/libmbtr                                                          
  copying dscribe/libmbtr/mbtrwrapper.cpp -> build/lib.linux-x86_64  
-3.7/dscribe/libmbtr                                                 
  running build_ext                                                  
  building 'dscribe.libacsf.acsfwrapper' extension                   
  creating build/temp.linux-x86_64-3.7                               
  creating build/temp.linux-x86_64-3.7/dscribe                       
  creating build/temp.linux-x86_64-3.7/dscribe/libacsf               
  gcc -pthread -B /u/csutton/conda-envs/py37/compiler_compat -Wl,--  
sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-pro  
totypes -fPIC -Idscribe/libacsf -I/u/csutton/conda-envs/py37/includ  
e/python3.7m -c dscribe/libacsf/acsfwrapper.cpp -o build/temp.linux  
-x86_64-3.7/dscribe/libacsf/acsfwrapper.o -std=c++11 -O3             
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is va  
lid for C/ObjC but not for C++                                       
  In file included from dscribe/libacsf/acsf.cpp:1,                  
                   from dscribe/libacsf/acsfwrapper.cpp:637:         
  dscribe/libacsf/acsf.h: In function ‘int __pyx_pf_7dscribe_7libac  
sf_11acsfwrapper_11ACSFWrapper___cinit__(__pyx_obj_7dscribe_7libacs  
f_11acsfwrapper_ACSFWrapper*)’:                                      
  dscribe/libacsf/acsf.h:14:7: warning: ‘<anonymous>’ is used unini  
tialized in this function [-Wuninitialized]                          
   class ACSF {                                                      
         ^~~~                                                        
  dscribe/libacsf/acsf.h:14:7: warning: ‘<anonymous>’ is used unini  
tialized in this function [-Wuninitialized]                          
  dscribe/libacsf/acsf.h:14:7: warning: ‘*((void*)&<anonymous> +8)’  
 is used uninitialized in this function [-Wuninitialized]            
  dscribe/libacsf/acsf.h:14:7: warning: ‘<anonymous>.ACSF::nG4’ is   
used uninitialized in this function [-Wuninitialized]                
  dscribe/libacsf/acsf.h:14:7: warning: ‘<anonymous>.ACSF::nG5’ is   
used uninitialized in this function [-Wuninitialized]                
  dscribe/libacsf/acsf.h:14:7: warning: ‘<anonymous>.ACSF::rCut’ is  
 used uninitialized in this function [-Wuninitialized]               
  g++ -pthread -shared -B /u/csutton/conda-envs/py37/compiler_compa  
t -L/u/csutton/conda-envs/py37/lib -Wl,-rpath=/u/csutton/conda-envs  
/py37/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_6  
4-3.7/dscribe/libacsf/acsfwrapper.o -o build/lib.linux-x86_64-3.7/d  
scribe/libacsf/acsfwrapper.cpython-37m-x86_64-linux-gnu.so           
  /u/csutton/conda-envs/py37/compiler_compat/ld: build/temp.linux-x  
86_64-3.7/dscribe/libacsf/acsfwrapper.o: unable to initialize decom  
press status for section .debug_info                                 
  /u/csutton/conda-envs/py37/compiler_compat/ld: build/temp.linux-x  
86_64-3.7/dscribe/libacsf/acsfwrapper.o: unable to initialize decom  
press status for section .debug_info                                 
  /u/csutton/conda-envs/py37/compiler_compat/ld: build/temp.linux-x  
86_64-3.7/dscribe/libacsf/acsfwrapper.o: unable to initialize decom  
press status for section .debug_info                                 
  /u/csutton/conda-envs/py37/compiler_compat/ld: build/temp.linux-x  
86_64-3.7/dscribe/libacsf/acsfwrapper.o: unable to initialize decom  
press status for section .debug_info                                 
  build/temp.linux-x86_64-3.7/dscribe/libacsf/acsfwrapper.o: file n  
ot recognized: file format not recognized                            
  collect2: error: ld returned 1 exit status                         
  error: command 'g++' failed with exit status 1                     
  ----------------------------------------                           
  ERROR: Failed building wheel for dscribe                           
  Running setup.py clean for dscribe                                 
Failed to build dscribe                                              
Installing collected packages: dscribe                               
  Found existing installation: dscribe 0.2.9                         
    Uninstalling dscribe-0.2.9:                                      
      Successfully uninstalled dscribe-0.2.9                         
  Running setup.py install for dscribe: started                      
    Running setup.py install for dscribe: finished with status 'err  
or'                                                                  
    ERROR: Complete output from command /u/csutton/conda-envs/py37/  
bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pi  
p-install-135uzlet/dscribe/setup.py'"'"';f=getattr(tokenize, '"'"'o  
pen'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'  
"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'  
 install --record /tmp/pip-record-9_718fyc/install-record.txt --sin  
gle-version-externally-managed --compile:                            
    ERROR: running install                                           
    running build                                                    
    running build_py                                                 
    creating build                                                   
    creating build/lib.linux-x86_64-3.7                              
    creating build/lib.linux-x86_64-3.7/dscribe                      
    copying dscribe/__init__.py -> build/lib.linux-x86_64-3.7/dscri  
be                                                                   
    creating build/lib.linux-x86_64-3.7/dscribe/core                 
    copying dscribe/core/system.py -> build/lib.linux-x86_64-3.7/ds  
cribe/core                                                           
    copying dscribe/core/__init__.py -> build/lib.linux-x86_64-3.7/  
dscribe/core                                                         
    copying dscribe/core/lattice.py -> build/lib.linux-x86_64-3.7/d  
scribe/core                                                          
    creating build/lib.linux-x86_64-3.7/dscribe/libacsf              
    copying dscribe/libacsf/__init__.py -> build/lib.linux-x86_64-3  
.7/dscribe/libacsf                                                   
    creating build/lib.linux-x86_64-3.7/dscribe/kernels              
    copying dscribe/kernels/__init__.py -> build/lib.linux-x86_64-3  
.7/dscribe/kernels                                                   
    copying dscribe/kernels/localsimilaritykernel.py -> build/lib.l  
inux-x86_64-3.7/dscribe/kernels                                      
    copying dscribe/kernels/averagekernel.py -> build/lib.linux-x86  
_64-3.7/dscribe/kernels                                              
    copying dscribe/kernels/rematchkernel.py -> build/lib.linux-x86  
_64-3.7/dscribe/kernels                                              
    creating build/lib.linux-x86_64-3.7/dscribe/libmbtr              
    copying dscribe/libmbtr/__init__.py -> build/lib.linux-x86_64-3  
.7/dscribe/libmbtr                                                   
    creating build/lib.linux-x86_64-3.7/dscribe/utils                
    copying dscribe/utils/species.py -> build/lib.linux-x86_64-3.7/  
dscribe/utils                                                        
    copying dscribe/utils/geometry.py -> build/lib.linux-x86_64-3.7  
/dscribe/utils                                                       
    copying dscribe/utils/stats.py -> build/lib.linux-x86_64-3.7/ds  
cribe/utils                                                          
    copying dscribe/utils/__init__.py -> build/lib.linux-x86_64-3.7  
/dscribe/utils                                                       
    creating build/lib.linux-x86_64-3.7/dscribe/descriptors          
    copying dscribe/descriptors/elementaldistribution.py -> build/l  
ib.linux-x86_64-3.7/dscribe/descriptors                              
    copying dscribe/descriptors/mbtr.py -> build/lib.linux-x86_64-3  
.7/dscribe/descriptors                                               
    copying dscribe/descriptors/coulombmatrix.py -> build/lib.linux  
-x86_64-3.7/dscribe/descriptors                                      
    copying dscribe/descriptors/__init__.py -> build/lib.linux-x86_  
64-3.7/dscribe/descriptors                                           
    copying dscribe/descriptors/sinematrix.py -> build/lib.linux-x8  
6_64-3.7/dscribe/descriptors                                         
    copying dscribe/descriptors/lmbtr.py -> build/lib.linux-x86_64-  
3.7/dscribe/descriptors                                              
    copying dscribe/descriptors/ewaldsummatrix.py -> build/lib.linu  
x-x86_64-3.7/dscribe/descriptors                                     
    copying dscribe/descriptors/soap.py -> build/lib.linux-x86_64-3  
.7/dscribe/descriptors                                               
    copying dscribe/descriptors/matrixdescriptor.py -> build/lib.li  
nux-x86_64-3.7/dscribe/descriptors                                   
    copying dscribe/descriptors/acsf.py -> build/lib.linux-x86_64-3  
.7/dscribe/descriptors                                               
    copying dscribe/descriptors/descriptor.py -> build/lib.linux-x8  
6_64-3.7/dscribe/descriptors                                         
    running egg_info                                                 
    writing dscribe.egg-info/PKG-INFO                                
    writing dependency_links to dscribe.egg-info/dependency_links.t  
xt                                                                   
    writing requirements to dscribe.egg-info/requires.txt            
    writing top-level names to dscribe.egg-info/top_level.txt        
    reading manifest file 'dscribe.egg-info/SOURCES.txt'             
    reading manifest template 'MANIFEST.in'                          
    writing manifest file 'dscribe.egg-info/SOURCES.txt'             
    creating build/lib.linux-x86_64-3.7/dscribe/ext                  
    copying dscribe/ext/celllist.cpp -> build/lib.linux-x86_64-3.7/  
dscribe/ext                                                          
    copying dscribe/ext/celllist.h -> build/lib.linux-x86_64-3.7/ds  
cribe/ext                                                            
    copying dscribe/ext/ext.cpp -> build/lib.linux-x86_64-3.7/dscri  
be/ext                                                               
    copying dscribe/ext/soapGTO.cpp -> build/lib.linux-x86_64-3.7/d  
scribe/ext                                                           
    copying dscribe/ext/soapGTO.h -> build/lib.linux-x86_64-3.7/dsc  
ribe/ext                                                             
    copying dscribe/ext/soapGeneral.cpp -> build/lib.linux-x86_64-3  
.7/dscribe/ext                                                       
    copying dscribe/ext/soapGeneral.h -> build/lib.linux-x86_64-3.7  
/dscribe/ext                                                         
    copying dscribe/libacsf/acsf.cpp -> build/lib.linux-x86_64-3.7/  
dscribe/libacsf                                                      
    copying dscribe/libacsf/acsf.h -> build/lib.linux-x86_64-3.7/ds  
cribe/libacsf                                                        
    copying dscribe/libacsf/acsfwrapper.cpp -> build/lib.linux-x86_  
64-3.7/dscribe/libacsf                                               
    copying dscribe/libmbtr/mbtr.cpp -> build/lib.linux-x86_64-3.7/  
dscribe/libmbtr                                                      
    copying dscribe/libmbtr/mbtr.h -> build/lib.linux-x86_64-3.7/ds  
cribe/libmbtr                                                        
    copying dscribe/libmbtr/mbtrwrapper.cpp -> build/lib.linux-x86_  
64-3.7/dscribe/libmbtr                                               
    running build_ext                                                
    building 'dscribe.libacsf.acsfwrapper' extension                 
    creating build/temp.linux-x86_64-3.7                             
    creating build/temp.linux-x86_64-3.7/dscribe                     
    creating build/temp.linux-x86_64-3.7/dscribe/libacsf             
    gcc -pthread -B /u/csutton/conda-envs/py37/compiler_compat -Wl,  
--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-p  
rototypes -fPIC -Idscribe/libacsf -I/u/csutton/conda-envs/py37/incl  
ude/python3.7m -c dscribe/libacsf/acsfwrapper.cpp -o build/temp.lin  
ux-x86_64-3.7/dscribe/libacsf/acsfwrapper.o -std=c++11 -O3           
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is   
valid for C/ObjC but not for C++                                     
    In file included from dscribe/libacsf/acsf.cpp:1,                
                     from dscribe/libacsf/acsfwrapper.cpp:637:       
    dscribe/libacsf/acsf.h: In function ‘int __pyx_pf_7dscribe_7lib  
acsf_11acsfwrapper_11ACSFWrapper___cinit__(__pyx_obj_7dscribe_7liba  
csf_11acsfwrapper_ACSFWrapper*)’:                                    
    dscribe/libacsf/acsf.h:14:7: warning: ‘<anonymous>’ is used uni  
nitialized in this function [-Wuninitialized]                        
     class ACSF {                                                    
           ^~~~                                                      
    dscribe/libacsf/acsf.h:14:7: warning: ‘<anonymous>’ is used uni  
nitialized in this function [-Wuninitialized]                        
    dscribe/libacsf/acsf.h:14:7: warning: ‘*((void*)&<anonymous> +8  
)’ is used uninitialized in this function [-Wuninitialized]          
    dscribe/libacsf/acsf.h:14:7: warning: ‘<anonymous>.ACSF::nG4’ i  
s used uninitialized in this function [-Wuninitialized]              
    dscribe/libacsf/acsf.h:14:7: warning: ‘<anonymous>.ACSF::nG5’ i  
s used uninitialized in this function [-Wuninitialized]              
    dscribe/libacsf/acsf.h:14:7: warning: ‘<anonymous>.ACSF::rCut’   
is used uninitialized in this function [-Wuninitialized]             
    g++ -pthread -shared -B /u/csutton/conda-envs/py37/compiler_com  
pat -L/u/csutton/conda-envs/py37/lib -Wl,-rpath=/u/csutton/conda-en  
vs/py37/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86  
_64-3.7/dscribe/libacsf/acsfwrapper.o -o build/lib.linux-x86_64-3.7  
/dscribe/libacsf/acsfwrapper.cpython-37m-x86_64-linux-gnu.so         
    /u/csutton/conda-envs/py37/compiler_compat/ld: build/temp.linux  
-x86_64-3.7/dscribe/libacsf/acsfwrapper.o: unable to initialize dec  
ompress status for section .debug_info                               
    /u/csutton/conda-envs/py37/compiler_compat/ld: build/temp.linux  
-x86_64-3.7/dscribe/libacsf/acsfwrapper.o: unable to initialize dec  
ompress status for section .debug_info                               
    /u/csutton/conda-envs/py37/compiler_compat/ld: build/temp.linux  
-x86_64-3.7/dscribe/libacsf/acsfwrapper.o: unable to initialize dec  
ompress status for section .debug_info                               
    /u/csutton/conda-envs/py37/compiler_compat/ld: build/temp.linux  
-x86_64-3.7/dscribe/libacsf/acsfwrapper.o: unable to initialize dec  
ompress status for section .debug_info                               
    build/temp.linux-x86_64-3.7/dscribe/libacsf/acsfwrapper.o: file  
 not recognized: file format not recognized                          
    collect2: error: ld returned 1 exit status                       
    error: command 'g++' failed with exit status 1                   
    ----------------------------------------                         
  Rolling back uninstall of dscribe                                  
  Moving to /talos/u/csutton/conda-envs/py37/lib/python3.7/site-pac  
kages/dscribe-0.2.9.dist-info/                                       
   from /talos/u/csutton/conda-envs/py37/lib/python3.7/site-package  
s/~scribe-0.2.9.dist-info                                            
  Moving to /talos/u/csutton/conda-envs/py37/lib/python3.7/site-pac  
kages/dscribe/                                                       
   from /talos/u/csutton/conda-envs/py37/lib/python3.7/site-package  
s/~scribe                                                            
ERROR: Command "/u/csutton/conda-envs/py37/bin/python -u -c 'import  
 setuptools, tokenize;__file__='"'"'/tmp/pip-install-135uzlet/dscri  
be/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__  
);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exe  
c(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/p  
ip-record-9_718fyc/install-record.txt --single-version-externally-m  
anaged --compile" failed with error code 1 in /tmp/pip-install-135u  
zlet/dscribe/                                              
```

This is installing via `poetry`, but `pip` gives the same errors.

**Comment by lauri-codes** [comment] 2020-02-06 22:02
Hi @sirmarcel,

I cannot reproduce this issue on a clean python3.7 install using pip globally or within a virtualenv.

Both in this issue and #43 a conda environment is used. Maybe this has something to do with it? I will take a look into this. Could you give a try by using virtualenv instead of a conda environment?

**Comment by sirmarcel** [comment] 2020-02-07 17:22
Hi -- okay, I will look into this. It might take a little way, as I'm knee-deep in a number of projects at the moment!

**Comment by lauri-codes** [comment] 2020-02-11 21:05
I can reproduce the issue when installing dscribe with conda from conda-forge (i.e. `conda install dscribe`). The issue is however limited to the conda package manager, and is not present when installing with pip. The easiest work-around for now is to install dscribe with pip instead. You can do this even inside a conda environment with:

```sh
conda install pip
pip install pybind11
pip install dscribe
```

I would suggest using this for now until I can figure out the issue with the conda distribution.

**Comment by lauri-codes** [comment] 2020-02-12 09:09
The issue is now also fixed in the conda package (there was actually an issue with the conda build system itself, not with dscribe). Just update to the latest version from conda-forge.

**Comment by sirmarcel** [comment] 2020-02-12 09:37
Hi Lauri, that's great! In my case I was installing it via `poetry` though (which should just be `pip` under the hood), but *inside* a `conda` environment.

**Comment by lauri-codes** [comment] 2020-02-12 09:47
Oh, my bad. I just saw `conda` in your filepath and leaped to an assumption :stuck_out_tongue: 

From the error I would guess that this might an issue with your compiler. Which version of GCC are you using? Maybe simply removing the package completely (make sure that that build/temp.linux-x86_64-3.7/dscribe/libacsf/acsfwrapper.o is removed) and switching to another compiler version could work?

**Comment by sirmarcel** [comment] 2020-02-14 13:59
Hi! No worries. :D 

I tried it with gcc6 and gcc9, the original report was with gcc8. It always looks like the same error. I'm not 100% sure I'm cleaning up after pip correctly, but I deleted `~/.caches/pip` after each attempt, and as far as I know, pip automatically cleans up if the build fails...

**Comment by lauri-codes** [comment] 2020-02-17 18:50
I'm quite sure that this has something to do with the platform or libraries in your HPC environment. What linux distribution is your HPC running? Can you attach the output of `pip list` within your conda env? If you are using slurm, can you attach the output of `module list`?

**Comment by lauri-codes** [comment] 2020-03-12 08:43
Closing this for now as inactive. Reopen as needed. Also, there is a new version (0.3.5) that you may try out (the wrapper code has been updated so maybe that helps?)

**Closed by lauri-codes** 2020-03-12 08:43 UTC

**Comment by sirmarcel** [comment] 2020-05-21 11:59
Hello, just a quick note: This error still occurred in my original setup even with `0.3.5`, but did not persist when I did the following:

- Clean conda environment with python 3.8, numpy, scipy
- `pip install dscribe`

I think the original problem might have been due to the awkward interaction of having a virtualenv inside a conda environment, or something like that. Still a bit mysterious, but pleased that it seems to work.
