### ISSUE TITLE
import error of `acsfwrapper` in version `0.3.2`

### ISSUE THREAD

**Issue by stenczelt** [SINGROUP/dscribe#43] opened 2020-02-06 17:07 UTC
`acsfwrapper` cannot be imported in version `0.3.2`

Here is the full conda env yml (as a .txt, otherwise github is not happy with it)
[conda_env.yml.txt](https://github.com/SINGROUP/dscribe/files/4166563/conda_env.yml.txt)

```
In [2]: from dscribe.descriptors import SOAP                                                                                                                                    
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-03308a51f02f> in <module>
----> 1 from dscribe.descriptors import SOAP

/opt/conda/envs/projection/lib/python3.7/site-packages/dscribe/descriptors/__init__.py in <module>
     15 """
     16 from dscribe.descriptors.descriptor import Descriptor
---> 17 from dscribe.descriptors.acsf import ACSF
     18 from dscribe.descriptors.mbtr import MBTR
     19 from dscribe.descriptors.lmbtr import LMBTR

/opt/conda/envs/projection/lib/python3.7/site-packages/dscribe/descriptors/acsf.py in <module>
     25 from ase import Atoms
     26 
---> 27 from dscribe.libacsf.acsfwrapper import ACSFWrapper
     28 import dscribe.utils.geometry
     29 

ModuleNotFoundError: No module named 'dscribe.libacsf.acsfwrapper'
```

The file exists in the env directory:
```
(projection) root@99c7ed173fe0:/opt/conda/envs/projection/lib/python3.7/site-packages/dscribe/libacsf# ls -l
total 364
-rw-rw-r-- 2 root root      0 Dec 25 22:17 __init__.py
drwxr-xr-x 2 root root   4096 Feb  6 12:42 __pycache__
-rw-rw-r-- 2 root root   6560 Dec 25 22:17 acsf.cpp
-rw-rw-r-- 2 root root   2082 Dec 25 22:17 acsf.h
-rw-rw-r-- 2 root root 241706 Dec 25 22:17 acsfwrapper.cpp
-rwxrwxr-x 2 root root 109696 Dec 25 22:17 acsfwrapper.cpython-37-x86_64-linux-gnu.so
```

but even in there it is not importable:
```
(projection) root@99c7ed173fe0:/opt/conda/envs/projection/lib/python3.7/site-packages/dscribe/libacsf# ipython
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:54:18) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import acsfwrapper                                                                                                                                                      
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d7b8cade2c17> in <module>
----> 1 import acsfwrapper

ModuleNotFoundError: No module named 'acsfwrapper'
```

**Comment by lauri-codes** [comment] 2020-02-06 22:04
Hi @stenczelt ,

I cannot reproduce this issue on a clean python3.7 install using pip globally or within a virtualenv.

Both in this issue and #42 a conda environment is used. Maybe this has something to do with it? I will take a look into this.

**Comment by lauri-codes** [comment] 2020-02-11 21:05
I can reproduce the issue when installing dscribe with conda from conda-forge (i.e. `conda install dscribe`). The issue is however limited to the conda package manager, and is not present when installing with pip. The easiest work-around for now is to install dscribe with pip instead. You can do this even inside a conda environment with:

```sh
conda install pip
pip install pybind11
pip install dscribe
```

I would suggest using this for now until I can figure out the issue with the conda distribution.

**Comment by lauri-codes** [comment] 2020-02-12 09:09
The issue is now also fixed in the conda package (there was actually an issue with the conda build system itself, not with dscribe). Just update to the latest version from conda-forge.

**Closed by lauri-codes** 2020-02-12 09:09 UTC
